TrainerNames:
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "DONALD@"
	db "LAURA@"
	db "POKéMANIAC@"
	db "ALAN@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "CASEY@"
	db "FISHERMAN@"
	db "SWIMMER@"
	db "CUE BALL@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "ROCKER@"
	db "CASEY@"
	db "DOUG@"
	db "BIRD KEEPER@"
	db "SURESH@"
	db "RIVAL1@"
	db "RICHARD@"
	db "CHIEF@"
	db "SCIENTIST@"
	db "RAGHU@"
	db "ROCKET@"
	db "KARIM@"
	db "LUCA@"
	db "BRUNO@"
	db "TABS@"
	db "KAREN@"
	db "RICHIE@"
	db "GEORGINA@"
	db "ALEX@"
	db "JAMES B@"
	db "SERENA@"
	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "LORELEI@"
	db "GUANGJIE@"
	db "AGATHA@"
	db "LANCE@"
